import StyledComponentsRegistry from '@/lib/registry';
import type { Metadata } from 'next';
import Navbar from '@/components/navbar/Navbar';
import { NextAuthProvider } from '../providers/sessionProviders';
import { Roboto } from 'next/font/google';
import FormHeader from '@/components/common/form-header/FormHeader';

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'eazyCV',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={roboto.className}>
      <NextAuthProvider>
        <StyledComponentsRegistry>
          <FormHeader />
          {children}
        </StyledComponentsRegistry>
      </NextAuthProvider>
    </div>
  );
}
