import StyledComponentsRegistry from '@/lib/registry';
import './globals.css';
import type { Metadata } from 'next';
import { NextAuthProvider } from './providers/sessionProviders';
import { Roboto } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const roboto = Roboto({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'eazyCV',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={roboto.className}>
        <NextIntlClientProvider messages={messages}>
          <NextAuthProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </NextAuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
